### ISSUE TITLE
--threads parameter in HOTSPOT.py doesn't work accordingly

### ISSUE THREAD

**Issue by GeoMicroSoares** [Orin-beep/HOTSPOT#1]
Hi there,

Great work with this tool! I'm testing it right now on my data and just realised that the `--threads` parameter in `HOTSPOT.py` doesn't work as it should. In my case I set it to 10 and it just defaulted to using all the available threads in the server. Just a heads up as this can generate some problems in the future...
Thanks!

**Comment by Orin-beep** [comment]
Hi, thank you for using HOTSPOT and identifying the bug!

I have modified line 90 of the ```HOTSPOT.py``` file, changing it to ```if device == torch.device('cpu'):```. This should ensure that the program now correctly sets the threads as required.

Please let me know if you have any further questions.

**Comment by Orin-beep** [comment]
Hi, thanks for your question. Do you mean that your MAG data for building the database lacks any taxonomy information?
