### ISSUE TITLE
Can I train a new model using different datasets？

### ISSUE THREAD

**Issue by ZoeLct** [Orin-beep/HOTSPOT#3]

**Comment by Orin-beep** [comment]
Hello! Thank you for your question. I am actively working on releasing a new version of HOTSPOT that will include the training function. I will make it available as soon as possible.

**Comment by Orin-beep** [comment]
Hi there! I apologize for my delayed response as I have been engaged in another project over the past few months. 

However, I'm pleased to inform you that a new version, V1.1, of HOTSPOT has been released. This latest version includes the feature of training your own custom models. You can easily train your model by following the tutorials provided in the **"Train your custom models"** section.

If you have any further questions, feel free to discuss with me!
